"""Add Indian GSTIN, mobile numbers, and loan purpose

Revision ID: 9804ec2b10b2
Revises: 45e30d0f5e35
Create Date: 2026-09-26 22:08:18.844512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9804ec2b10b2'
down_revision: Union[str, Sequence[str], None] = '45e30d0f5e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.alter_column('admins', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_index(op.f('ix_admins_mobile_number'), 'admins', ['mobile_number'], unique=True)
    op.add_column('customers', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.alter_column('customers', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_index(op.f('ix_customers_mobile_number'), 'customers', ['mobile_number'], unique=True)
    op.add_column('finance_companies', sa.Column('gstin', sa.String(length=20), nullable=True))
    op.add_column('finance_companies', sa.Column('pan_number', sa.String(length=15), nullable=True))
    op.add_column('finance_companies', sa.Column('state', sa.String(length=60), nullable=True))
    op.add_column('finance_companies', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_finance_companies_gstin'), 'finance_companies', ['gstin'], unique=True)
    op.add_column('loans', sa.Column('purpose', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'purpose')
    op.drop_index(op.f('ix_finance_companies_gstin'), table_name='finance_companies')
    op.drop_column('finance_companies', 'pincode')
    op.drop_column('finance_companies', 'state')
    op.drop_column('finance_companies', 'pan_number')
    op.drop_column('finance_companies', 'gstin')
    op.drop_index(op.f('ix_customers_mobile_number'), table_name='customers')
    op.alter_column('customers', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('customers', 'mobile_number')
    op.drop_index(op.f('ix_admins_mobile_number'), table_name='admins')
    op.alter_column('admins', 'hashed_password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('admins', 'mobile_number')
    # ### end Alembic commands ###
